In [3]:
from keras import backend as K
import tensorflow as tf

In [9]:
%%time
# Creates a graph.
with tf.device('/gpu:0'):
    a = tf.random_uniform((5000,100000), name = 'adrian')
    b = tf.random_uniform((5000,100000), name = 'adrfian')
c = a*b
# Creates a session with log_device_placement set to True.
session_config = tf.ConfigProto(
    log_device_placement=True,
    allow_soft_placement = True,
    device_count = {'CPU' : 1, 'GPU' : 2},
    gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.95,
                             allow_growth=True)
)

session_conf = tf.ConfigProto(
      intra_op_parallelism_threads=0,
      inter_op_parallelism_threads=0)

sess = tf.Session(config=session_config)
# Runs the op.
print(sess.run(c))

[[0.01003072 0.03799122 0.05194293 ... 0.04202351 0.30687118 0.06683221]
 [0.0849879  0.12126558 0.10126951 ... 0.08752832 0.52767855 0.2849743 ]
 [0.21755765 0.16124827 0.02222606 ... 0.6631206  0.7700652  0.00725602]
 ...
 [0.05499918 0.6460368  0.1030094  ... 0.3617629  0.03508424 0.16406491]
 [0.0136449  0.16348642 0.44491908 ... 0.11109305 0.06909923 0.25870216]
 [0.52065414 0.43924776 0.85702413 ... 0.18549687 0.01481432 0.24146673]]
CPU times: user 8.73 s, sys: 1.35 s, total: 10.1 s
Wall time: 889 ms


In [47]:
with tf.device('/gpu:0'):
    a = tf.random_uniform((50000,100000), name = 'adrian')
    b = tf.random_uniform((50000,100000), name = 'adrfian')
c = a*b

session_config = tf.ConfigProto(
    log_device_placement=True,
    allow_soft_placement = True,
    device_count = {'CPU' : 1, 'GPU' : 0},
    gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.95,
                             allow_growth=True)
)

In [48]:
sess = tf.Session(config=session_config)

In [49]:
%%time
print(sess.run(c))

[[0.26052606 0.3287073  0.04848393 ... 0.07185129 0.29662627 0.32543394]
 [0.05587957 0.872188   0.28273362 ... 0.10100031 0.17324594 0.30045575]
 [0.00799042 0.49983233 0.01870096 ... 0.18555394 0.23680018 0.1531397 ]
 ...
 [0.51930505 0.02967984 0.11699698 ... 0.22318022 0.25830242 0.4229563 ]
 [0.7842522  0.093909   0.04294299 ... 0.0830019  0.20160563 0.09792839]
 [0.27889898 0.5689475  0.63331765 ... 0.2316052  0.03705591 0.50679433]]
CPU times: user 1min 24s, sys: 12.5 s, total: 1min 36s
Wall time: 7.8 s


In [34]:
sess.close()

In [ ]:
device_count = {'CPU' : 1, 'GPU' : 1})

In [7]:
import numpy as np

In [22]:
tf.reset_default_graph()

In [23]:
sess.close()

In [8]:
from numba import cuda
cuda.select_device(0)
cuda.close()

E0201 12:45:13.433435 140256148731712 driver.py:318] Call to cuInit results in CUDA_ERROR_UNKNOWN


CudaSupportError: Error at driver init: 
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN: